### PR TITLE
use radiobuttons to decide which datetype should be used

### PR DESCRIPTION
**Pull request by Murmele**

### CODE REVIEW

**Comment by H-4ND-H** [comment]
@Murmele I checked the code, As for the resize, I changed the code so that when the date time is shown, we have no horizontal change in `QLineEdit`s, would you like to preserve a blank space vertically for `QDateTimeEdit` too, or leave it as it is which expands / shrink vertically?

Plus I notice it does not handle git commit with title and body well in commit message section.
a
b

**Comment by Murmele** [comment]
> @Murmele I checked the code, As for the resize, I changed the code so that when the date time is shown, we have no horizontal change in `QLineEdit`s, would you like to preserve a blank space vertically for `QDateTimeEdit` too, or leave it as it is which expands / shrink vertically?
> 
> Plus I notice it does not handle git commit with title and body well in commit message section. a b

@H-4ND-H looks great thanks! How do feel better, with white space or without? I think you can bring this into your other branch and working there ^^

**Comment by Murmele** [comment]
> Plus I notice it does not handle git commit with title and body well in commit message section.

Yes currently in Gittyup we don't have title description differentiation. But this is another point we can handle in a second approach

**Comment by H-4ND-H** [comment]
> @H-4ND-H looks great thanks! How do feel better, with white space or without? I think you can bring this into your other branch and working there ^^

Glad to help, I will, Personally I think it is better without white spaces. Will finalize the code and push to my branch.

**Comment by Murmele** [comment]
You can work on top of this branch and then merging this merge request or?

**Comment by H-4ND-H** [comment]
I pulled your changes to my local `Amend` branch and worked on top of that.

**Comment by Murmele** [comment]
ok great

**Pull request closed without merging**
